### ISSUE TITLE
Print help when no command is given

### ISSUE THREAD

**Issue by hojelse** [joglr/katpis#16]
When you call `katpis` with out any arguments the program terminates without printing anything.

Maybe print help and commands and options or version number?

**Comment by hojelse** [comment]
Resolved in commit 72a2670

**Comment by joglr** [comment]
Seems to not be the case. When I run the latest version without any arguments, I don't get any output. 

![image](https://user-images.githubusercontent.com/1959615/98855009-a1cb2100-245b-11eb-9066-ee6e34b27e78.png)
